config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :restaurants, foreign_key: "user_id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
    after_action :verify_authorized, except: :index, unless: :skip_pundit?
    after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

    # Uncomment when you *really understand* Pundit!
    # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
    # def user_not_authorized
    #   flash[:alert] = "You are not authorized to perform this action."
    #   redirect_to(root_path)
    # end

    private

    def skip_pundit?
      devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    @restaurants = Restaurant.all
    @three_restaurants = @restaurants.sample(3)
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_restaurant, only: [:edit, :update, :show, :destroy]

  def index
    @restaurants = policy_scope(Restaurant).all
  end

  def new
    @restaurant = Restaurant.new
    authorize @restaurant
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.user = current_user
    authorize @restaurant
    if @restaurant.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    authorize @restaurant
  end

  def update
    if @restaurant.update(restaurant_params)
      authorize @restaurant
      redirect_to restaurants_path
    else
      render :edit
    end
  end

  def destroy
    @restaurant.destroy
    authorize @restaurant
    redirect_to restaurants_path
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    authorize @restaurant
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :stars, :review)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/restaurant_helper.rb
module RestaurantHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hungronymous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.rawgit.com/michalsnik/aos/2.1.1/dist/aos.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lexend+Deca&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div id="home-video-wrapper">
  <%= video_tag "restaurant.mp4", autoplay: true, loop: true, mute: true, id: "home-video" %>
  <div>
    <h1 id="home">Hungronymous</h1>
  </div>
  <div>
    <h4 id="home">Probably the best food critic in the world</h4>
  </div>
  <div>
    <a class="btn btn-primary" href="restaurants#index" role="button">Enter</a>
  </div>
</div>

<!-- <div class="featured-restaurants"> -->
  <h1>Recently reviewed restaurants</h1>
  <% @three_restaurants.each do |restaurant| %>
    <div class="carousel slide" data-ride="carousel">
      <div class="carousel-inner">
        <div class="carousel-item">
          <%= image_tag "https://picsum.photos/id/310/200/300" %>
          <div class="carousel-caption d-none d-md-block">
            <h5><%= restaurant.name %></h5>
            <p><%= restaurant.review %></p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<!-- </div> -->

app/views/restaurants/_form.html.erb
<div class="form-text">
  <%= simple_form_for @restaurant do |f| %>
    <%= f.input :name %>
    <%= f.input :stars, collection: 1..5 %>
    <%= f.input :review, as: :text %>
    <%= f.button :submit, "Add review", class: "form-button btn btn-primary"%>
  <% end %>
</div>

app/views/restaurants/create.html.erb
<h1>Restaurants#create</h1>
<p>Find me in app/views/restaurants/create.html.erb</p>

app/views/restaurants/destroy.html.erb
<h1>Restaurants#destroy</h1>
<p>Find me in app/views/restaurants/destroy.html.erb</p>

app/views/restaurants/edit.html.erb
<div class="container">
  <h1 id="form-title">Edit your review</h1>
  <%= render "form" %>
</div>

app/views/restaurants/index.html.erb
<div class="container">
  <h1>Hungronymous reviews</h1>
  <% @restaurants.each do |restaurant| %>
    <%= link_to restaurant_path(restaurant) do %>
      <div class="card-product" data-aos="zoom-out-right">
        <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
        <div class="card-product-infos">
          <h2><%= restaurant.name %></h2>
          <p><%= restaurant.review[0..140] %></p>
        </div>
      </div>
    <% end %>
  <% end %>
</div>
<script src="https://cdn.rawgit.com/michalsnik/aos/2.1.1/dist/aos.js"></script>

app/views/restaurants/new.html.erb
<div class="container">
  <h1 id="form-title">Add a restaurant</h1>
  <%= render "form" %>
</div>

app/views/restaurants/show.html.erb
<div class="container restaurant-details">
  <h1 class="show-header"><%= @restaurant.name %></h1>
  <p>Rating: <%= @restaurant.stars %></p>
  <p>Review: <%= @restaurant.review %></p>
  <% if current_user == @restaurant.user %>
    <%= link_to "Edit review", edit_restaurant_path, class: "btn btn-primary" %>
    <%= link_to "Delete review", restaurant_path, method: :delete, class: "btn btn-primary" %>
  <% end %>
</div>

app/views/restaurants/update.html.erb
<h1>Restaurants#update</h1>
<p>Find me in app/views/restaurants/update.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "logo" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", restaurants_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <% if policy(Restaurant).create? %>
            <%= link_to "Add review", new_restaurant_path, class: "nav-link" %>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign-up", "/users/sign_up", class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>